// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArmKdeGTeHxZQBo4AUtjUs1dQEwzpEiDE',
    appId: '1:607393282246:web:170001dc715949e785bfc7',
    messagingSenderId: '607393282246',
    projectId: 'fir-chat-app-84bd4',
    authDomain: 'fir-chat-app-84bd4.firebaseapp.com',
    storageBucket: 'fir-chat-app-84bd4.appspot.com',
    measurementId: 'G-B2PEJZVKGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXGSA4_cSXWU0sh7315i7U1HVfaQy1WRM',
    appId: '1:607393282246:android:57b13a757fe144ff85bfc7',
    messagingSenderId: '607393282246',
    projectId: 'fir-chat-app-84bd4',
    storageBucket: 'fir-chat-app-84bd4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAErCocsIOO5Vl8B5lrUMzKAn4cPUk-pls',
    appId: '1:607393282246:ios:bb7d64eb0af45ff785bfc7',
    messagingSenderId: '607393282246',
    projectId: 'fir-chat-app-84bd4',
    storageBucket: 'fir-chat-app-84bd4.appspot.com',
    iosBundleId: 'com.example.firebaseChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAErCocsIOO5Vl8B5lrUMzKAn4cPUk-pls',
    appId: '1:607393282246:ios:bb7d64eb0af45ff785bfc7',
    messagingSenderId: '607393282246',
    projectId: 'fir-chat-app-84bd4',
    storageBucket: 'fir-chat-app-84bd4.appspot.com',
    iosBundleId: 'com.example.firebaseChatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArmKdeGTeHxZQBo4AUtjUs1dQEwzpEiDE',
    appId: '1:607393282246:web:1c5b0ad4bd0ed6ab85bfc7',
    messagingSenderId: '607393282246',
    projectId: 'fir-chat-app-84bd4',
    authDomain: 'fir-chat-app-84bd4.firebaseapp.com',
    storageBucket: 'fir-chat-app-84bd4.appspot.com',
    measurementId: 'G-B246CFKEYD',
  );
}
